### ISSUE TITLE
src/magnetic.jl

### ISSUE THREAD

**Issue by mfherbst** [singularitti/Spglib.jl#164]
Is there any particular reason why `src/magnetic.jl` is not actually included. I would love to use `get_symmetry_with_collinear_spin` in DFTK.

**Comment by singularitti** [comment]
Hi Michael, I was working on the magnetic part. But I don't have many tests for them. Would it be possible for you to provide some examples that I could utilize?

**Comment by mfherbst** [comment]
We use it during collinear spin calculations, but I'm afraid that I right now don't have an example handy that could be directly employed for testing in spglib.

**Comment by singularitti** [comment]
OK, I've found some tests [here](https://github.com/spglib/spglib/blob/8fab0b0a3272256aa3190181375009db82dd9b38/test/functional/python/test_magnetic_dataset.py#L250) and [here](https://github.com/spglib/spglib/blob/8fab0b0a3272256aa3190181375009db82dd9b38/test/functional/fortran/test_fortran_spg_get_symmetry_with_site_tensors.F90). I will debug and test them soon.

**Comment by singularitti** [comment]
Hi @mfherbst, the magnetic module is now ready to go on the main branch's commit head. Please have a try.

**Comment by mfherbst** [comment]
The `get_symmetry_with_collinear_spin` function seems to work as I expect.

**Comment by mfherbst** [comment]
Implemented in DFTK in https://github.com/JuliaMolSim/DFTK.jl/pull/924

**Comment by singularitti** [comment]
Glad to hear that!
