### ISSUE TITLE
Spglib v2.2.0 has made changes that break some tests

### ISSUE THREAD

**Issue by singularitti** [singularitti/Spglib.jl#178]
Dear Spglib.jl users,

I would like to inform you of a recent issue encountered with Spglib.jl following an upgrade to spglib_jll.jl version v2.2.0+0. [Some tests have failed post-upgrade](https://github.com/singularitti/Spglib.jl/actions/runs/7268729978), indicating potential compatibility or functional issues.

Upon initial investigation, I observed that corresponding Python code in Spglib has also undergone changes. This leads me to believe that the root of the problem might lie within the changes made to Spglib's underlying C code, rather than being specific to spglib_jll.jl & Spglib.jl alone.

Currently, I am unable to allocate time to debug this issue in detail. My next step is to reach out to the official Spglib development team for insights and possible solutions.

In the meantime, I recommend that users revert spglib_jll.jl to version v2.1.0+0 to ensure stability and avoid the issues presented by the latest update. I apologize for any inconvenience caused and appreciate your patience and understanding as we work towards resolving this matter.

Thank you for your cooperation.

**Comment by singularitti** [comment]
@mfherbst @thchr @kbarros @qiaojunfeng @zhubonan @harrisonlabollita @jaemolihm

**Comment by thchr** [comment]
How about just restricting spglib_jll to v2.1 in the Project.toml of Spglib.jl for the time being?

**Comment by singularitti** [comment]
I could, but I'm not sure if that is a bug or a feature yet. I need to have a look at what changes might cause it.

**Comment by singularitti** [comment]
Hi everyone, I have restricted spglib_jll.jl up to 2.1 in the latest release. We will re-enable 2.2.0+ in Spglib.jl in 0.10.0+ since it is a breaking change.
