### ISSUE TITLE
find_primitive results in errors if the result is 3 atoms

### ISSUE THREAD

**Issue by kfgarrity** [singularitti/Spglib.jl#99]
**Describe the bug**
find_primitive results in the error message "ERROR: ambiguous `positions` size 3×3! Use a vector of `Vector`s instead!"
in some cases where the result has 3 atoms.

**To Reproduce**
using Spglib
A = [6.0 0 6; 6 0 6; 0 6 6]
coords = [0.0 0.0 0.0;0.5 0.5 0.5; 0.75 0.75 0.75]
coords_vec = [coords[i,:] for i in 1:3]
atoms = ["Na", "Cl", "Na"]
cell = Spglib.Cell(A, coords_vec, atoms)  #results in error

#also results in error
cell_std = Spglib.standardize_cell(cell, to_primitive=true)

**Comment by hsugawa8651** [comment]
This "bug" is due to the following lines, which throw the exception when the `positions` is a type of `AbstractMatrix` with the size of `(3,3)`  : https://github.com/singularitti/Spglib.jl/blob/50183cc4c20ff486b1701b3e0452586bf00a8fe8/src/model.jl#L32-L33

I believe it is serve to throw the exception under the above situation. 
Or rewrite the following (and similar) line to instantiate `Cell` with `_positions` converted to the type of vector  of `Vector`s to detour the above lines.
https://github.com/singularitti/Spglib.jl/blob/50183cc4c20ff486b1701b3e0452586bf00a8fe8/src/standardize.jl#L42

**Comment by kfgarrity** [comment]
Sorry, I messed up the bug report. This is what it should say


```
using Spglib
A = [6.0 0 6; 6 0 6; 0 6 6]
coords = [0.0 0.0 0.0;0.5 0.5 0.5; 0.75 0.75 0.75]
coords_vec = [coords[i,:] for i in 1:3]
atoms = ["Na", "Cl", "Na"]
cell = Spglib.Cell(A, coords_vec, atoms)

#results in error
cell_prim = Spglib.find_primitive(cell)

#also results in error
cell_std = Spglib.standardize_cell(cell, to_primitive=true)
```

**Comment by singularitti** [comment]
Does #107 solve your problem? @kfgarrity

**Comment by singularitti** [comment]
Hi @kfgarrity, I have tried this example in [Python `spglib`](), it does not work either. Could you try by yourself?

```python
import spglib

lattice = np.array([[6.0, 0.0, 6.0], [6.0, 0.0, 6.0], [0.0, 6.0, 6.0]])
positions = np.array([[0.0, 0.0, 0.0], [0.5, 0.5, 0.5], [0.75, 0.75, 0.75]])
atoms = [1, 2, 1]

spglib.find_primitive((lattice, pos, atoms))  # return None
```

**Comment by kfgarrity** [comment]
Okay, I think the new version of the code is working. Regarding the python, there was an issue with the example. The lattice vectors I gave you are degenerate (sorry), which is why the python version didn't produce output.

This python example works

```
import numpy as np
import spglib

lattice = np.array([[6.0, 0.0, 6.0], [6.0, 6.0, 0.0], [0.0, 6.0, 6.0]])
positions = np.array([[0.0, 0.0, 0.0], [0.5, 0.5, 0.5], [0.75, 0.75, 0.75]])
atoms = [1, 2, 1]

output = spglib.find_primitive((lattice, positions, atoms))`
```

When I try the julia equivalent with the current code, it now works as well:

```
using Spglib
A = [6.0 0 6; 6 6 0; 0 6 6]
coords = [0.0 0.0 0.0;0.5 0.5 0.5; 0.75 0.75 0.75]
coords_vec = [coords[i,:] for i in 1:3]
atoms = ["Na", "Cl", "Na"]
cell = Spglib.Cell(A, coords_vec, atoms)

#now works
cell_prim = Spglib.find_primitive(cell)

#now works as well
cell_std = Spglib.standardize_cell(cell, to_primitive=true)
```

So I think the issue is resolved.
